class AddColumnToSheets < ActiveRecord::Migration[7.1]
  def change
    add_column :sheets, :Nom, :string
    add_column :sheets, :Nature, :string
    add_column :sheets, :Clan, :string
    add_column :sheets, :Joueur, :string
    add_column :sheets, :Attitude, :string
    add_column :sheets, :Génération, :integer
    add_column :sheets, :Chronique, :string
    add_column :sheets, :Concept, :string
    add_column :sheets, :Refuge, :string
    add_column :sheets, :Force, :integer
    add_column :sheets, :Dextérité, :integer
    add_column :sheets, :Vigueur, :integer
    add_column :sheets, :Charisme, :integer
    add_column :sheets, :Manipulation, :integer
    add_column :sheets, :Apparence, :integer
    add_column :sheets, :Perception, :integer
    add_column :sheets, :Intelligence, :integer
    add_column :sheets, :Astuce, :integer
    add_column :sheets, :Expression, :integer
    add_column :sheets, :Vigilances, :integer
    add_column :sheets, :Athlétisme, :integer
    add_column :sheets, :Bagarre, :integer
    add_column :sheets, :Esquive, :integer
    add_column :sheets, :Empathie, :integer
    add_column :sheets, :Intimidation, :integer
    add_column :sheets, :Passe, :integer
    add_column :sheets, :Commandement, :integer
    add_column :sheets, :Subterfuge, :integer
    add_column :sheets, :Animaux, :integer
    add_column :sheets, :Archerie, :integer
    add_column :sheets, :Artisanats, :integer
    add_column :sheets, :Equitation, :integer
    add_column :sheets, :Etiquette, :integer
    add_column :sheets, :Furtivité, :integer
    add_column :sheets, :Commerce, :integer
    add_column :sheets, :Mêlée, :integer
    add_column :sheets, :Représentation, :integer
    add_column :sheets, :Survie, :integer
    add_column :sheets, :Erudition, :integer
    add_column :sheets, :Investigation, :integer
    add_column :sheets, :Droit, :integer
    add_column :sheets, :Linguistique, :integer
    add_column :sheets, :Médecine, :integer
    add_column :sheets, :Occulte, :integer
    add_column :sheets, :Sagesse, :integer
    add_column :sheets, :Politique, :integer
    add_column :sheets, :Sénéchal, :integer
    add_column :sheets, :Théologie, :integer
    add_column :sheets, :Volonté, :integer
    add_column :sheets, :Consciences, :integer
    add_column :sheets, :Maitrise, :integer
    add_column :sheets, :Courage, :integer
    add_column :sheets, :Livres, :integer
    add_column :sheets, :Deniers, :integer
  end
end
